CREATE TABLE IF NOT EXISTS tbl_user (

  id       INT NOT NULL AUTO_INCREMENT,
  nickname VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,

  PRIMARY KEY (id)

) TYPE=INNODB DEFAULT CHARSET=utf8;